name: jira-evidence-example

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
  push:
    branches:
      - carmit_examples
  pull_request:
      branches:
        - carmit_examples
permissions:
  id-token: write
  contents: read

jobs:
  docker-build-with-jira-evidence:
    runs-on: ubuntu-latest
    steps:
      - name: Install jfrog cli
        id:   setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
        with:
         oidc-provider-name: jfrog-github-oidc

      - uses: actions/checkout@v4
          

      - name: Get git commit messages
        run: |
            # Get the latest commit that triggered the build
            START_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "START_COMMIT=$START_COMMIT"
          
            #git log --oneline "$START_COMMIT"..HEAD
            echo "git log --oneline"
            git log --oneline
          
            echo "git log -1 --format=%H %s"
            git log -1 --format="%H %s"
            START_COMMIT1=$(git log -1 --format="%H %s")
            echo "START_COMMIT1=$START_COMMIT1"
            second_element=$(echo "$START_COMMIT1" | cut -d' ' -f2)
            echo "$second_element"
            # Check if the second element matches the JIRA ID format
            if [[ $second_element =~ ^[A-Z]+-[0-9]+$ ]]; then
                echo "The second element is a valid JIRA ID: $second_element"
                ./examples/jira-transition-example/bin/jira-transition-checker-linux-amd64 aaa $second_element
            else
                echo "The second element is not a valid JIRA ID"
            fi