name: jira-evidence-example

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
  push:
    branches:
      - carmit_examples
  pull_request:
      branches:
        - carmit_examples
permissions:
  id-token: write
  contents: read

jobs:
  docker-build-with-jira-evidence:
    runs-on: ubuntu-latest
    steps:
      - name: Install jfrog cli
        id:   setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
        with:
         oidc-provider-name: jfrog-github-oidc

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history for all branches and tags

      - name: Get git commit messages
        run: |
            # Get the latest commit that triggered the build
            START_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "START_COMMIT=$START_COMMIT"            
            git log --oneline "$START_COMMIT"..HEAD    
            
            # Get the commit messages since the last tag or since the base commit in PR
            COMMIT_MESSAGES=$(git log --oneline "$START_COMMIT"..HEAD)
            
            echo "Commit messages that triggered this build:"
            echo "$COMMIT_MESSAGES"

