name: zap-evidence-example

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
  push:
    branches:
      - carmit_examples
  pull_request:
      branches:
        - carmit_examples
permissions:
  id-token: write
  contents: read


jobs:
  ran-and-zap-scan-evidence:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: 'test-docker-local'
      IMAGE_NAME: 'my-very-cool-image:${{ github.run_number }}'
      BUILD_NAME: 'zap-evidence-example'
    steps:
      - name: Display workflow and job names
        run: |
          echo "Workflow name: $GITHUB_WORKFLOW"
          echo "Job name: $GITHUB_JOB"

      - name: Install jfrog cli
        id:   setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
        with:
         oidc-provider-name: jfrog-github-oidc

      - uses: actions/checkout@v4

      - name: start webgoat
        run: |
          docker run -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -e TZ=Europe/Amsterdam webgoat/webgoat

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080/WebGoat/login'
          fail_action: false


